### ISSUE TITLE
В выходном массиве second_name и last_name перепутаны местами

### ISSUE THREAD

**Issue by dmitrystas** [MihanEntalpo/FIO-Analyzer#1]
Похоже нужно поменять местами тут
> 		$found[0] = $this->searchIn( "first_names", $p, $min, $max, $edge );
> 		$found[1] = $this->searchIn( "last_names", $p, $min, $max, $edge );
> 		$found[2] = $this->searchIn( "second_names", $p, $min, $max, $edge );
1-й и 2-й ключ, сделать
> 		$found[0] = $this->searchIn( "first_names", $p, $min, $max, $edge );
> 		$found[1] = $this->searchIn( "second_names", $p, $min, $max, $edge );
> 		$found[2] = $this->searchIn( "last_names", $p, $min, $max, $edge );

**Comment by MihanEntalpo** [comment]
Принял PR в котором это исправляется
